services:
  postgres:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-lucap}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-lucap_pass}
      POSTGRES_DB: ${POSTGRES_DB:-lucap}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/18/docker
  storage:
    image: dxos/garage:layout-v9 # Or minio/minio
    container_name: lucap_storage
    restart: unless-stopped
    volumes:
      - lucap_meta:/var/lib/garage/meta
      - lucap_data:/var/lib/garage/data
    ports:
      - "3900:3900" # S3 API Endpoint
    environment:
      - GARAGE_RPC_SECRET=${GARAGE_RPC_SECRET:-lucap_secret}
  mail:
    image: axllent/mailpit:latest
    restart: unless-stopped
    ports:
      - "${MAIL_PORT_DOCKER}:1025"
      - "${MAIL_UI_PORT}:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  pgdata:
  lucap_meta:
  lucap_data: